# Generated by Django 6.0.3 on 2026-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('laptop_model', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Battery', 'Battery'), ('Screen', 'Screen'), ('Other', 'Other')], max_length=20)),
                ('problem_description', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
