# Generated by Django 6.0.3 on 2026-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_laptoprental_payment_method_laptoprental_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoprental',
            name='laptop_specs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptopsale',
            name='laptop_specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
