# Generated by Django 6.0.3 on 2026-03-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_laptoprental_address_laptoprental_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptoprental',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='laptopsale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
