# Generated by Django 6.0.3 on 2026-03-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
